Repository SukBakJi/SukBakJi-iOS, pull requests merged in 2025-04, with the labels that each got.

#242 Feat/notification
  Sukbakji.xcodeproj/project.pbxproj
  Sukbakji/DataLayer/Extensions/FCMTokenManager+.swift
  Sukbakji/DataLayer/Repositories/CalendarRepository.swift
  Sukbakji/DataLayer/Repositories/FCMRepository.swift
  Sukbakji/DesignSystem/.DS_Store
  Sukbakji/DesignSystem/Components/Calendar/AllDeleteView.swift
  Sukbakji/DesignSystem/Components/Calendar/EditAlarmView.swift
  Sukbakji/DesignSystem/Components/Calendar/UnivView.swift
  Sukbakji/DesignSystem/Components/Common/NotificationView.swift
  Sukbakji/DesignSystem/Components/Home/HomeView.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivCalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/Reactor/HomeReactor.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/FavoriteBoardTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/ViewModel/MyProfileViewModel.swift
  Sukbakji/PresentationLayer/Sources/Main/MainTabViewController.swift
  Sukbakji/PresentationLayer/Sources/Main/NotificationTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Main/NotificationViewController.swift
  Sukbakji/SUKBAKJI/Sources/AppDelegate.swift
Labels: documentation, enhancement

#246 Feat/calendar
  Sukbakji/DataLayer/APIs/APIConstants.swift
  Sukbakji/DataLayer/Repositories/CalendarRepository.swift
  Sukbakji/PresentationLayer/Sources/Calendar/.DS_Store
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/EditMyAlarmViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/SetAlarmViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivCalendarTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivCalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/AlarmViewModel.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/UnivViewModel.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
  Sukbakji/PresentationLayer/Sources/SignUp/ViewControllers/CompleteViewController.swift
Labels: documentation, enhancement

#247 Feat/calendar
  Sukbakji/DataLayer/Repositories/CalendarRepository.swift
  Sukbakji/DesignSystem/Components/Calendar/UnivRecruitView.swift
  Sukbakji/DesignSystem/Extensions/Notification+.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/SetAlarmViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarDetailTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/UpComingCalendarCollectionViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/EditUnivCalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivCalendarTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivCalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivRecruitViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivSearchTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Univ/UnivSearchViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/AlarmViewModel.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/CalendarViewModel.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/UnivViewModel.swift
  Sukbakji/PresentationLayer/Sources/Home/Reactor/HomeReactor.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/AdvertiseCollectionViewCell.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/HotPostTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/EditInfoViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/EditPWViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/MypageViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/ProfileTabViewController.swift
Labels: documentation, enhancement

#249 [feat] 연구실 후기 작성 페이지에서 탭바 숨김
  Sukbakji/PresentationLayer/Sources/Directory/LabDetailReviewViewController.swift
Labels: enhancement

#255 [feat] 댓글 신고하기 UI 완성
  Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift
Labels: enhancement

#260 [feat] 게시물 삭제 기능+키보드 내림
  Sukbakji.xcodeproj/project.pbxproj
  Sukbakji/DesignSystem/Extensions/UIApplication+.swift
  Sukbakji/PresentationLayer/Sources/Board/BoardEditViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/BoardModel/BoardDeleteModel.swift
  Sukbakji/PresentationLayer/Sources/Board/BoardWriteViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift
Labels: enhancement

#262 [feat] 디렉토리 메인 화면 우측 상단 버튼 활성화
  Sukbakji/PresentationLayer/Sources/Directory/DirectoryMainViewController.swift
  Sukbakji/PresentationLayer/Sources/Directory/DirectorySearchViewController.swift
Labels: documentation

#264 [feat] 게시판에서 알림화면 navigate 구현
  Sukbakji/PresentationLayer/Sources/Board/BoardViewController.swift
Labels: enhancement

#265 Feat/calendar
  Sukbakji.xcodeproj/project.pbxproj
  Sukbakji/DesignSystem/Components/Calendar/CalendarView.swift
  Sukbakji/DesignSystem/Components/Calendar/EditAlarmView.swift
  Sukbakji/DesignSystem/Components/Calendar/SetAlarmView.swift
  Sukbakji/DesignSystem/Extensions/TimeHelper+.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/AlarmDateCollectionViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/EditMyAlarmViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Alarm/MyAlarmTableViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarMainCollectionViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarViewController.swift
  Sukbakji/PresentationLayer/Sources/Calendar/ViewModel/CalendarViewModel.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/EditInfoViewController.swift
Labels: documentation

#268 [fix] 커스텀 탭바 적용 후 게시판, 디렉토리 UI 묻히는 문제 해결
  Sukbakji/PresentationLayer/Sources/Board/Admission/BoardAdmissionViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/BoardViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/Doctoral/BoardDoctoralViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/Main/BoardQnAViewController.swift
  Sukbakji/PresentationLayer/Sources/Board/Master/BoardMasterViewController.swift
  Sukbakji/PresentationLayer/Sources/Directory/LabDetailReviewViewController.swift
  Sukbakji/PresentationLayer/Sources/Directory/LabDetailViewController.swift
  Sukbakji/PresentationLayer/Sources/Main/MainTabViewController.swift
Labels: bug

#271 [feat] 마이페이지 문의하기 버튼 추가 및 게시글, 댓글 신고 팝업창 추가 (#254)
  Sukbakji/DesignSystem/Components/Home/HomeView.swift
  Sukbakji/DesignSystem/Components/Home/MyPageView.swift
  Sukbakji/PresentationLayer/Sources/Board/Main/DummyBoardDetail.swift
  Sukbakji/PresentationLayer/Sources/Board/ViewModel/ReportViewModel.swift
  Sukbakji/PresentationLayer/Sources/Home/View/Home/HomeViewController.swift
  Sukbakji/PresentationLayer/Sources/Home/View/MyPage/MypageViewController.swift
Labels: enhancement

#277 Feat/calendar
  Sukbakji/DesignSystem/Assets.xcassets/Home_Calendar/Sukbakji_Left.imageset/Contents.json
  Sukbakji/DesignSystem/Assets.xcassets/Home_Calendar/Sukbakji_Left.imageset/Sukbakji_Left.png
  Sukbakji/DesignSystem/Assets.xcassets/Home_Calendar/Sukbakji_RightDisabled.imageset/Contents.json
  Sukbakji/DesignSystem/Assets.xcassets/Home_Calendar/Sukbakji_RightDisabled.imageset/Sukbakji_RightDisabled.png
  Sukbakji/DesignSystem/Components/Calendar/DateView.swift
  Sukbakji/DesignSystem/Components/Chat/ChatNavigaionBarView.swift
  Sukbakji/DesignSystem/Components/Chat/MessageInputView.swift
  Sukbakji/PresentationLayer/Sources/Calendar/.DS_Store
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarMainCollectionViewCell.swift
  Sukbakji/PresentationLayer/Sources/Calendar/View/Calendar/CalendarViewController.swift
Labels: enhancement
